import { Roboto_Flex } from "next/font/google";
import { draftMode } from "next/headers";
import LiveVisualEditing from "@/loader/LiveVisualEditing";
import Navbar from "@/components/global/Navbar";
import Footer from "@/components/global/Footer";
import type { Metadata } from "next";
import "../globals.css";

const roboto = Roboto_Flex({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Support",
  description: "Generated by create next app",
};

export default function SupportLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        {children}
        <Footer />
        {draftMode().isEnabled && <LiveVisualEditing />}
      </body>
    </html>
  );
}
