import { Inter } from "next/font/google";
import { draftMode } from "next/headers";
import LiveVisualEditing from "@/components/LiveVisualEditing";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Business Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        {draftMode().isEnabled && <LiveVisualEditing />}
        <Footer />
      </body>
    </html>
  );
}
