import { Inter } from "next/font/google";
import { draftMode } from "next/headers";
import LiveVisualEditing from "@/loader/LiveVisualEditing";
import Navbar from "@/components/global/Navbar";
import Footer from "@/components/global/Footer";
import type { Metadata } from "next";
import "../globals.css";

// TODO figure out why Sanity Template on GH does this?
// const HomePagePreview = dynamic(
//   () => import('@/components/pages/home/HomePagePreview'),
// )
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Business Page",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        {draftMode().isEnabled && <LiveVisualEditing />}
      </body>
    </html>
  );
}
